### ISSUE TITLE
Data format of new-record process

### ISSUE THREAD

**Issue by r3399r** [r3399r/sirius#9]
思考一個資料處理起來方便、易懂的儲存樣式，以 JSON 的形式

例如
```
{
    type: "wolf",
    player: {
        guard: "Andy",
        wizard: "Brandon",
        ...
    }
    ...
}
```

留言在下方即可
只是草稿，未來隨時都可以改

**Comment by coolcold1898** [comment]
{
    type: "wolf-guard",
    player: [
        "Alex", "Bai", "Cindy", "David", "Eric", "Fred",
        "George", "Herman", "Iris", "Jenny", "Kevin", "Lily"
    ],
    role: [
        "Seer", "witch", "hunter", "guard", "wolf-king", "wolf"
        "wolf", "wolf", "villager", "villager", "villager", "villager"
    ],
    night: [
        {
            kill: 1,
            rescue: "Y",
            poison: "None",
            check: 2,
            guard: "None",
            hunter-shoot: "inactive",
            wolf-king-shoot: "inactive"
        },
        {
            kill: 2,
            rescue: "N",
            poison: 6,
            check: "die",
            guard: 4,
            hunter-shoot: "inactive",
            wolf-king-shoot: "die"
        }......   
    ],
    sheriff: [
        {
            run-for: [1,5,9],
            withdraw: [9],
            first-vote: {
                1: "run-for",
                2: 1,
                3: 1,
                4: "give-up",
                5: "run-for"......
            },
            second-vote: {
                1: "None",
                2: "None"......
            }
        }
    ],
    daytime: [
        {
            correct:{
                seer: ["good",2],
                witch: {silver: 1, poisoned: "None"},
                guard: "N",
                hunter: "N"
            },
            pretend:{
                seer: {
                    number: 5,
                    report: ["bad",2] 
                },
                witch: {
                    number: 6,
                    report: {silver: 5, poisoned: "None"}
                },
                guard: "N",
                hunter: "N"
            },
            sacrifice: {
                seer: "N",
                witch: "N",
                guard: "N",
                hunter: "N"
            },
            death: {
                state: "exile",
                number: [1:[5,"None"], 2:[5,"None"]......]
            },
            skill: {
                hunter: "inactive",
                wolf-king: 1
            }
        },
        {
            correct:{
                seer: "die",
                witch: "die",
                guard: ["None","non-report"],
                hunter: "N"
            },
            pretend:{
                seer: "N",
                witch: "N",
                guard: "N",
                hunter: "N"
            },
            sacrifice: {
                seer: "N",
                witch: "N",
                guard: "N",
                hunter: "N"
            },
            death: {
                state: "self-destruct after voting",
                number: 7
            },
            skill: {
                hunter: "inactive",
                wolf-king: "die"
            }
        }......  
    ],
}

**Comment by coolcold1898** [comment]
{
    type: "wolf-guard",
    player: [
        "Alex", "Bai", "Cindy", "David", "Eric", "Fred",
        "George", "Herman", "Iris", "Jenny", "Kevin", "Lily"
    ],
    role: [
        "Seer", "witch", "hunter", "guard", "wolf-king", "wolf"
        "wolf", "wolf", "villager", "villager", "villager", "villager"
    ],
    night: [
        {
            kill: 1,
            rescue: "Y",
            poison: "None",
            check: 2,
            guard: "None",
            hunter-shoot: "inactive",
            wolf-king-shoot: "inactive"
        },
        {
            kill: 2,
            rescue: "N",
            poison: 6,
            check: "die",
            guard: 4,
            hunter-shoot: "inactive",
            wolf-king-shoot: "die"
        }......   
    ],
    sheriff: [
        {
            run-for: [1,5,9],
            withdraw: [9],
            first-vote: {
                1: "run-for",
                2: 1,
                3: 1,
                4: "give-up",
                5: "run-for"......
            },
            second-vote: {
                1: "None",
                2: "None"......
            }
        }
    ],
    daytime: [
        {
            correct:{
                seer: ["good",2],
                witch: {silver: 1, poisoned: "None"},
                guard: "N",
                hunter: "N"
            },
            pretend:{
                seer: {
                    number: 5,
                    report: ["bad",2] 
                },
                witch: {
                    number: 6,
                    report: {silver: 5, poisoned: "None"}
                },
                guard: "N",
                hunter: "N"
            },
            sacrifice: {
                seer: "N",
                witch: "N",
                guard: "N",
                hunter: "N"
            },
            death: {
                state: "exile",
                number: [1:[5,"None"], 2:[5,"None"]......]
            },
            skill: {
                hunter: "inactive",
                wolf-king: 1
            }
        },
        {
            correct:{
                seer: "die",
                witch: "die",
                guard: ["None","non-report"],
                hunter: "N"
            },
            pretend:{
                seer: "N",
                witch: "N",
                guard: "N",
                hunter: "N"
            },
            sacrifice: {
                seer: "N",
                witch: "N",
                guard: "N",
                hunter: "N"
            },
            death: {
                state: "self-destruct after voting",
                number: 7
            },
            skill: {
                hunter: "inactive",
                wolf-king: "die"
            }
        }......  
    ],
}

**Comment by coolcold1898** [comment]
qwe

**Comment by r3399r** [comment]
{
  a: 1
}

**Comment by coolcold1898** [comment]
'''
{
    type: "wolf",
    player: {
        guard: "Andy",
        wizard: "Brandon",
        ...
    }
    ...
}
'''

**Comment by coolcold1898** [comment]
'''{
    a
}'''

**Comment by coolcold1898** [comment]
"""
{
    a
}
""""

**Comment by coolcold1898** [comment]
```
{
    type: "wolf",
    player: {
        guard: "Andy",
        wizard: "Brandon",
        ...
    }
    ...
}
```

**Comment by coolcold1898** [comment]
```
{
    type: "wolf-guard",
    player: [
        {id: 1, player: "Alex", role: "seer" },
        {id: 2, player: "Bai",  role: "witch"},
        {id: 3, player: "Cindy", role : "hunter"},
        {id: 4, player: "David", role : "guard"},
        {id: 5, player: "Eric", role: "wolf-king"},
        {id: 6, player: "Fred", role: "wolf"}......
    ],
    night: [
        {
            kill: 1,
            rescue: "Y",
            poison: "None",
            check: 2,
            guard: "None",
            hunter-shoot: "inactive",
            wolf-king-shoot: "inactive"
        },
        {
            kill: 2,
            rescue: "N",
            poison: 6,
            check: "die",
            guard: 4,
            hunter-shoot: "inactive",
            wolf-king-shoot: "die"
        }......   
    ],
    sheriff: [
        {
            run-for: [1,5,9],
            withdraw: [9],
            first-vote: {
                1: "run-for",
                2: 1,
                3: 1,
                4: "give-up",
                5: "run-for"......
            },
            second-vote: {
                1: "None",
                2: "None"......
            }
        }
    ],
    daytime: [
        {
            correct:{
                seer: {status:"good", number: 2},
                witch: {silver: 1, poisoned: "None"},
                guard: "N",
                hunter: "N"
            },
            pretend:{
                seer: {
                    number: 5,
                    report: {status:"bad", number: 2} 
                },
                witch: {
                    number: 6,
                    report: {silver: 5, poisoned: "None"}
                },
                guard: "N",
                hunter: "N"
            },
            sacrifice: {
                seer: "N",
                witch: "N",
                guard: "N",
                hunter: "N"
            },
            death: {
                state: "exile",
                number: [[5,"None"], [5,"None"]......]
            },
            skill: {
                hunter: "inactive",
                wolf-king: 1
            }
        },
        {
            correct:{
                seer: "die",
                witch: "die",
                guard: ["None","non-report"],
                hunter: "N"
            },
            pretend:{
                seer: "N",
                witch: "N",
                guard: "N",
                hunter: "N"
            },
            sacrifice: {
                seer: "N",
                witch: "N",
                guard: "N",
                hunter: "N"
            },
            death: {
                state: "self-destruct after voting",
                number: 7
            },
            skill: {
                hunter: "inactive",
                wolf-king: "die"
            }
        }......  
    ],
}
```

**Comment by r3399r** [comment]
@coolcold1898 我在思考，這個結構是否夠改成
```
{
    type: "wolf-guard",
    player: [{
            id: 1,
            name: "Alex",
            role: "seer",
            
        },
        {id: 2, player: "Bai",  role: "witch"},
        {id: 3, player: "Cindy", role : "hunter"},
       ......
    ]
}
```
